apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-alpha
  labels:
    app: k8s-alpha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-alpha
  template:
    metadata:
      labels:
        app: k8s-alpha
    spec:
      containers:
        - name: cont1
          image: 343546983409.dkr.ecr.us-east-1.amazonaws.com/alpha-repo:9-4592844
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: ENV
              value: "dev"
